import { Box, Typography, Paper, Chip } from "@mui/material";
import { motion } from "framer-motion";
import ProcessingHeader from "../../components/processing-header";

const particleO3 = `${import.meta.env.BASE_URL}thumbnail_new_O3.png`;
const particlePM25 = `${import.meta.env.BASE_URL}thumbnail_new_PM2.5.png`;
const particlePM10 = `${import.meta.env.BASE_URL}thumbnail_new_PM10.png`;
const particleCO2 = `${import.meta.env.BASE_URL}thumbnail_new_CO2.png`;
const particleNO2 = `${import.meta.env.BASE_URL}thumbnail_new_NO2.png`;
const health = `${import.meta.env.BASE_URL}health.png`;

type ParticleId = "pm10" | "pm25" | "o3" | "co" | "no2";

type ParticleMeta = {
  id: ParticleId;
  label: string;
  description: string;
  healthImpact: string;
  image: string;
};

const baseParticles: ParticleMeta[] = [
  {
    id: "pm10",
    label: "PM10",
    description:
      "Coarse particulate matter with a diameter of 10 μm or less. Often dust, pollen, or mold.",
    healthImpact:
      "Irritates the eyes, nose, and throat. Can worsen asthma and other respiratory conditions.",
    image: particlePM10,
  },
  {
    id: "pm25",
    label: "PM2.5",
    description:
      "Fine particulate matter 2.5 μm or smaller. Generated by combustion, smoke, and industrial emissions.",
    healthImpact:
      "Enters deep into lungs and bloodstream, increasing risk of heart and lung disease.",
    image: particlePM25,
  },
  {
    id: "o3",
    label: "Ozone (O₃)",
    description:
      "Ground-level ozone created when sunlight reacts with pollutants from vehicles and industry.",
    healthImpact:
      "Triggers chest tightness and coughing, and inflames the airways even in healthy people.",
    image: particleO3,
  },
  {
    id: "co",
    label: "Carbon Monoxide (CO)",
    description:
      "Colorless, odorless, and toxic gas produced by incomplete combustion of fossil fuels and biomass.",
    healthImpact:
      "Exposure to high levels can cause headaches, dizziness, and impaired judgment. Can be fatal in high concentrations.",
    image: particleCO2,
  },
  {
    id: "no2",
    label: "Nitrogen Dioxide (NO₂)",
    description:
      "Reddish-brown gas from vehicle exhaust and power plants. A key contributor to smog.",
    healthImpact:
      "Irritates airways, reduces lung function, and can increase susceptibility to infections.",
    image: particleNO2,
  },
];

const particleColors: Record<
  ParticleId,
  { backgroundColor: string; textColor: string }
> = {
  pm10: {
    backgroundColor: "#FFF427", // Yellow (keep existing)
    textColor: "#000000", // Black text
  },
  pm25: {
    backgroundColor: "#E54C4C", // Red
    textColor: "#FFFFFF", // White text
  },
  o3: {
    backgroundColor: "#54E0F7", // Teal
    textColor: "#000000", // Black text
  },
  co: {
    backgroundColor: "#B7ED32", // Green
    textColor: "#000000", // White text
  },
  no2: {
    backgroundColor: "#8E5B00", // Orange
    textColor: "#FFFFFF", // Black text
  },
};

/**
 * Discover Summary page displaying all air quality particles in a summary format.
 * Shows all particles with their descriptions and health impacts in a grid layout.
 */
const DiscoverSummaryPage = () => {
  return (
    <Box
      component="main"
      role="main"
      sx={{
        minHeight: "100vh",
        minWidth: "100vw",
        position: "relative",
        overflow: "auto",
        backgroundColor: "#FAFAFA",
      }}
    >
      <Box
        sx={{
          position: "relative",
          zIndex: 210,
          display: "flex",
          justifyContent: "center",
        }}
      >
        <ProcessingHeader
          currentStep={0}
          prevRoute="/examine"
          nextRoute="/aqi"
        />
      </Box>

      <Box
        sx={{
          maxWidth: 1400,
          mx: "auto",
          px: { xs: 2, md: 4 },
          py: { xs: 4, md: 8 },
        }}
      >
        <Typography
          variant="h3"
          sx={{
            textAlign: "center",
            mb: 6,
            fontWeight: 500,
            fontFamily: "Inter",
            fontSize: { xs: "1.75rem", md: "2rem" },
            color: "#1a1a1a",
          }}
        >
          Here are all the particles side by side
        </Typography>

        <Box
          sx={{
            display: "grid",
            gridTemplateColumns: {
              xs: "1fr",
              md: "repeat(2, 1fr)",
              lg: "repeat(3, 1fr)",
            },
            gap: 4,
            mb: 6,
          }}
        >
          {baseParticles.map((particle, index) => (
            <motion.div
              key={particle.id}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: index * 0.1 }}
            >
              <Paper
                elevation={3}
                sx={{
                  p: 3,
                  borderRadius: 3,
                  height: "100%",
                  display: "flex",
                  flexDirection: "column",
                  transition: "transform 0.2s ease, box-shadow 0.2s ease",
                  "&:hover": {
                    transform: "translateY(-4px)",
                    boxShadow: 6,
                  },
                  backgroundColor: "#FFFFFF",
                }}
              >
                <Box
                  sx={{
                    display: "flex",
                    alignItems: "center",
                    gap: 2,
                    mb: 2,
                  }}
                >
                  <Box
                    component="img"
                    src={particle.image}
                    alt={`${particle.label} particle icon`}
                    sx={{
                      width: 64,
                      height: 64,
                      objectFit: "contain",
                    }}
                  />
                  <Chip
                    label={particle.label}
                    sx={{
                      fontWeight: 600,
                      fontSize: "0.95rem",
                      backgroundColor:
                        particleColors[particle.id].backgroundColor,
                      color: particleColors[particle.id].textColor,
                      height: 32,
                    }}
                  />
                </Box>

                <Typography
                  variant="body1"
                  sx={{
                    mb: 2,
                    fontWeight: 500,
                    color: "#333333",
                    lineHeight: 1.6,
                  }}
                >
                  {particle.description}
                </Typography>

                <Box
                  sx={{
                    mt: "auto",
                    pt: 2,
                    borderTop: "1px solid #E0E0E0",
                  }}
                >
                  <Box
                    sx={{
                      display: "flex",
                      gap: 1,
                      alignItems: "center",
                      mb: 1.5,
                    }}
                  >
                    <Box
                      component="img"
                      src={health}
                      alt="Health Impact"
                      sx={{ width: 20, height: 20 }}
                    />
                    <Typography
                      variant="body2"
                      sx={{
                        fontWeight: 600,
                        color: "#666666",
                        textTransform: "uppercase",
                        letterSpacing: 0.5,
                        fontSize: "0.75rem",
                      }}
                    >
                      Health Impact
                    </Typography>
                  </Box>
                  <Typography
                    variant="body2"
                    sx={{
                      color: "#555555",
                      lineHeight: 1.6,
                      pl: 3,
                    }}
                  >
                    {particle.healthImpact}
                  </Typography>
                </Box>
              </Paper>
            </motion.div>
          ))}
        </Box>
      </Box>
    </Box>
  );
};

export default DiscoverSummaryPage;
