import { useMemo, useState, useEffect, useCallback } from "react";
import { Box, Typography, Paper, Chip, Fab } from "@mui/material";
import { motion } from "framer-motion";
import magnifierSrc from "../../assets/magnifier.png";
import particleO3 from "../../assets/particles_O3.png";
import particlePM25 from "../../assets/particles_PM2.5.png";
import particlePM10 from "../../assets/particles_PM10.png";
import particleCO2 from "../../assets/particles-C02.png";
import particleNO2 from "../../assets/particles-NO2.png";
import ArrowForward from "@mui/icons-material/ArrowForward";
import { useNavigate } from "react-router-dom";

type ParticleId = "pm10" | "pm25" | "o3" | "co" | "no2";

type ParticleMeta = {
  id: ParticleId;
  label: string;
  description: string;
  healthImpact: string;
  image: string;
};

type ParticleInstance = ParticleMeta & {
  top: string;
  left: string;
};

const baseParticles: ParticleMeta[] = [
  {
    id: "pm10",
    label: "PM10",
    description:
      "Coarse particulate matter with a diameter of 10 μm or less. Often dust, pollen, or mold.",
    healthImpact:
      "Irritates the eyes, nose, and throat. Can worsen asthma and other respiratory conditions.",
    image: particlePM10,
  },
  {
    id: "pm25",
    label: "PM2.5",
    description:
      "Fine particulate matter 2.5 μm or smaller. Generated by combustion, smoke, and industrial emissions.",
    healthImpact:
      "Enters deep into lungs and bloodstream, increasing risk of heart and lung disease.",
    image: particlePM25,
  },
  {
    id: "o3",
    label: "Ozone (O₃)",
    description:
      "Ground-level ozone created when sunlight reacts with pollutants from vehicles and industry.",
    healthImpact:
      "Triggers chest tightness and coughing, and inflames the airways even in healthy people.",
    image: particleO3,
  },
  {
    id: "co",
    label: "Carbon Monoxide (CO)",
    description:
      "Colorless, odorless, and toxic gas produced by incomplete combustion of fossil fuels and biomass.",
    healthImpact:
      "Exposure to high levels can cause headaches, dizziness, and impaired judgment. Can be fatal in high concentrations.",
    image: particleCO2,
  },
  {
    id: "no2",
    label: "Nitrogen Dioxide (NO₂)",
    description:
      "Reddish-brown gas from vehicle exhaust and power plants. A key contributor to smog.",
    healthImpact:
      "Irritates airways, reduces lung function, and can increase susceptibility to infections.",
    image: particleNO2,
  },
];

const ExaminePage = () => {
  const particleInstances = useMemo<ParticleInstance[]>(
    () =>
      baseParticles.map((particle) => ({
        ...particle,
        top: `${Math.round(15 + Math.random() * 60)}%`,
        left: `${Math.round(15 + Math.random() * 60)}%`,
      })),
    []
  );

  const [activeParticle, setActiveParticle] = useState<ParticleInstance | null>(
    null
  );
  const [cursorPosition, setCursorPosition] = useState({ x: 0, y: 0 });
  const [cursorVisible, setCursorVisible] = useState(false);
  const [hoveredId, setHoveredId] = useState<ParticleId | null>(null);
  const [infoPosition, setInfoPosition] = useState<{
    x: number;
    y: number;
  } | null>(null);
  const navigate = useNavigate();

  useEffect(() => {
    console.debug("hoveredId changed", hoveredId);
  }, [hoveredId]);

  const handleActivate = (
    particle: ParticleInstance,
    event: React.MouseEvent<HTMLElement> | React.TouchEvent<HTMLElement>
  ) => {
    const target = event.currentTarget as HTMLElement;
    const rect = target.getBoundingClientRect();
    console.debug("activate", particle.id, "target:", target.tagName);
    setActiveParticle(particle);
    setHoveredId(particle.id);
    setInfoPosition({ x: rect.left + rect.width / 2, y: rect.top + 100 });
  };

  const handlePointerLeave = (particleId?: ParticleId) => {
    const idToClear = particleId ?? hoveredId;
    console.debug("pointer leave", idToClear);
    if (idToClear) {
      setHoveredId((current) => (current === idToClear ? null : current));
    }
    setActiveParticle(null);
    setInfoPosition(null);
  };

  const handleNavigateNext = useCallback(() => {
    navigate("/more");
  }, [navigate]);

  return (
    <Box
      component="main"
      role="main"
      sx={{
        minHeight: "100vh",
        minWidth: "100vw",
        position: "relative",
        overflow: "hidden",
        bgcolor: "#ffffff",
        cursor: "none",
      }}
      onPointerMove={(event) => {
        setCursorPosition({ x: event.clientX, y: event.clientY });
        setCursorVisible(true);
      }}
      onPointerLeave={() => {
        setCursorVisible(false);
      }}
    >
      {particleInstances.map((particle) => {
        const isActive = hoveredId === particle.id;
        return (
          <motion.img
            key={particle.id}
            src={particle.image}
            alt={`${particle.label} particle icon`}
            initial={{ opacity: 0.55, scale: 0.9 }}
            animate={{
              opacity: isActive ? 1 : 0.55,
              scale: isActive ? 1.05 : 0.9,
            }}
            transition={{ duration: 0.2, ease: "easeOut" }}
            onPointerEnter={(event) => handleActivate(particle, event as never)}
            onPointerDown={(event) => handleActivate(particle, event as never)}
            onFocus={(event) => handleActivate(particle, event as never)}
            onPointerLeave={() => handlePointerLeave(particle.id)}
            onBlur={() => handlePointerLeave(particle.id)}
            tabIndex={0}
            style={{
              position: "absolute",
              top: particle.top,
              left: particle.left,
              width: 96,
              height: 96,
              pointerEvents: "auto",
              filter: isActive ? "blur(0px)" : "blur(5px)",
              transition:
                "filter 220ms ease, opacity 200ms ease, transform 200ms ease",
            }}
          />
        );
      })}

      {activeParticle && infoPosition && (
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 8 }}
          transition={{ duration: 0.18, ease: "easeOut" }}
          style={{
            position: "fixed",
            top: infoPosition.y,
            left: infoPosition.x,
            transform: "translate(-50%, -100%)",
            pointerEvents: "none",
            zIndex: 200,
          }}
        >
          <Paper
            elevation={6}
            sx={{
              px: 2.5,
              py: 2,
              maxWidth: 320,
              borderRadius: 3,
              boxShadow: 6,
              pointerEvents: "none",
            }}
          >
            <Chip
              label={activeParticle.label}
              color="success"
              sx={{ mb: 1.5, fontWeight: 600 }}
              aria-hidden
            />
            <Typography variant="body1" sx={{ mb: 1.5, fontWeight: 500 }}>
              {activeParticle.description}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              {activeParticle.healthImpact}
            </Typography>
          </Paper>
        </motion.div>
      )}

      <motion.img
        src={magnifierSrc}
        alt="Magnifying glass cursor"
        initial={{ opacity: 0 }}
        animate={
          cursorVisible ? { opacity: 1, scale: 3 } : { opacity: 0, scale: 0.9 }
        }
        transition={{ duration: 0.2, ease: "easeOut" }}
        style={{
          position: "fixed",
          top: cursorPosition.y - 48,
          left: cursorPosition.x - 32,
          width: 96,
          height: 96,
          pointerEvents: "none",
          zIndex: 20,
        }}
      />
      <motion.div
        initial={{ x: -48, y: 24, opacity: 0 }}
        animate={{ x: 24, opacity: 1 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        style={{ position: "absolute", top: 0, left: 0, pointerEvents: "none" }}
      >
        <Paper
          elevation={6}
          sx={{
            px: 3,
            py: 2,
            maxWidth: 400,
            backgroundColor: "rgba(86, 200, 83, 0.95)",
          }}
        >
          <Typography
            variant="body1"
            sx={{
              fontWeight: 400,
              fontSize: "1.5rem",
              color: "#fbfbfb",
              lineHeight: 1.4,
            }}
          >
            Hover over each particle to learn more{" "}
          </Typography>
        </Paper>
      </motion.div>
      <motion.div
        style={{
          position: "absolute",
          bottom: 32,
          right: 32,
          pointerEvents: "auto",
        }}
      >
        <Fab
          color="success"
          aria-label="Show results"
          onClick={handleNavigateNext}
          sx={{
            width: 72,
            height: 72,
            backgroundColor: "#1c8c3a",
            "&:hover": { backgroundColor: "#56C853" },
          }}
        >
          <ArrowForward sx={{ fontSize: 36 }} />
        </Fab>
      </motion.div>
    </Box>
  );
};

export default ExaminePage;
