import { useMemo, useState, useEffect } from "react";
import { Box, Typography, Paper, Chip } from "@mui/material";
import { motion } from "framer-motion";
import magnifierSrc from "../../assets/magnifier.png";
import ProcessingHeader from "../../components/processing-header";
const particleO3 = `${import.meta.env.BASE_URL}thumbnail_new_O3.png`;
const particlePM25 = `${import.meta.env.BASE_URL}thumbnail_new_PM2.5.png`;
const particlePM10 = `${import.meta.env.BASE_URL}thumbnail_new_PM10.png`;
const particleCO2 = `${import.meta.env.BASE_URL}thumbnail_new_CO2.png`;
const particleNO2 = `${import.meta.env.BASE_URL}thumbnail_new_NO2.png`;
type ParticleId = "pm10" | "pm25" | "o3" | "co" | "no2";
const health = `${import.meta.env.BASE_URL}health.png`;

type ParticleMeta = {
  id: ParticleId;
  label: string;
  description: string;
  healthImpact: string;
  image: string;
};

type ParticleInstance = ParticleMeta & {
  top: string;
  left: string;
};

const baseParticles: ParticleMeta[] = [
  {
    id: "pm10",
    label: "PM10",
    description:
      "Coarse particulate matter with a diameter of 10 μm or less. Often dust, pollen, or mold.",
    healthImpact:
      "Irritates the eyes, nose, and throat. Can worsen asthma and other respiratory conditions.",
    image: particlePM10,
  },
  {
    id: "pm25",
    label: "PM2.5",
    description:
      "Fine particulate matter 2.5 μm or smaller. Generated by combustion, smoke, and industrial emissions.",
    healthImpact:
      "Enters deep into lungs and bloodstream, increasing risk of heart and lung disease.",
    image: particlePM25,
  },
  {
    id: "o3",
    label: "Ozone (O₃)",
    description:
      "Ground-level ozone created when sunlight reacts with pollutants from vehicles and industry.",
    healthImpact:
      "Triggers chest tightness and coughing, and inflames the airways even in healthy people.",
    image: particleO3,
  },
  {
    id: "co",
    label: "Carbon Monoxide (CO)",
    description:
      "Colorless, odorless, and toxic gas produced by incomplete combustion of fossil fuels and biomass.",
    healthImpact:
      "Exposure to high levels can cause headaches, dizziness, and impaired judgment. Can be fatal in high concentrations.",
    image: particleCO2,
  },
  {
    id: "no2",
    label: "Nitrogen Dioxide (NO₂)",
    description:
      "Reddish-brown gas from vehicle exhaust and power plants. A key contributor to smog.",
    healthImpact:
      "Irritates airways, reduces lung function, and can increase susceptibility to infections.",
    image: particleNO2,
  },
];

const particleColors: Record<
  ParticleId,
  { backgroundColor: string; textColor: string }
> = {
  pm10: {
    backgroundColor: "#FFF427", // Yellow (keep existing)
    textColor: "#000000", // Black text
  },
  pm25: {
    backgroundColor: "#E54C4C", // Red
    textColor: "#FFFFFF", // White text
  },
  o3: {
    backgroundColor: "#54E0F7", // Teal
    textColor: "#000000", // Black text
  },
  co: {
    backgroundColor: "#B7ED32", // Green
    textColor: "#000000", // White text
  },
  no2: {
    backgroundColor: "#8E5B00", // Orange
    textColor: "#FFFFFF", // Black text
  },
};

const ExaminePage = () => {
  /**
   * Generates non-overlapping particle positions using collision detection.
   * Particles are 96x96 pixels, so we ensure minimum spacing between them.
   */
  const particleInstances = useMemo<ParticleInstance[]>(() => {
    // Assume viewport dimensions for collision detection calculations
    // Using a standard desktop viewport size
    const viewportWidth = 1920;
    const viewportHeight = 1080;

    // Particle dimensions in pixels
    const particleSize = 96;
    // Minimum spacing between particles (particle size + padding)
    const minSpacing = particleSize + 20;

    // Define valid placement area (avoiding info box on left and buttons on bottom)
    const minTopPercent = 15;
    const maxTopPercent = 75; // Leave space for bottom buttons
    const minLeftPercent = 30; // Avoid info box area (~400px)
    const maxLeftPercent = 80;

    const placedParticles: Array<{ top: number; left: number }> = [];
    const maxAttempts = 1000;

    return baseParticles.map((particle) => {
      let attempts = 0;
      let topPercent = minTopPercent;
      let leftPercent = minLeftPercent;
      let isValidPosition = false;

      // Try to find a non-overlapping position
      while (!isValidPosition && attempts < maxAttempts) {
        topPercent = Math.round(
          minTopPercent + Math.random() * (maxTopPercent - minTopPercent)
        );
        leftPercent = Math.round(
          minLeftPercent + Math.random() * (maxLeftPercent - minLeftPercent)
        );

        // Convert percentages to pixel coordinates for collision detection
        const topPx = (topPercent / 100) * viewportHeight;
        const leftPx = (leftPercent / 100) * viewportWidth;

        // Check collision with all previously placed particles
        isValidPosition = placedParticles.every((placed) => {
          const placedTopPx = (placed.top / 100) * viewportHeight;
          const placedLeftPx = (placed.left / 100) * viewportWidth;

          // Calculate distance between particle centers
          const centerTopPx = topPx + particleSize / 2;
          const centerLeftPx = leftPx + particleSize / 2;
          const placedCenterTopPx = placedTopPx + particleSize / 2;
          const placedCenterLeftPx = placedLeftPx + particleSize / 2;

          const distanceX = Math.abs(centerLeftPx - placedCenterLeftPx);
          const distanceY = Math.abs(centerTopPx - placedCenterTopPx);

          // Check if particles overlap (distance between centers should be >= minSpacing)
          return distanceX >= minSpacing || distanceY >= minSpacing;
        });

        attempts++;
      }

      // If we couldn't find a position after max attempts, use the last generated position
      // This should rarely happen with 5 particles
      const finalTop = topPercent;
      const finalLeft = leftPercent;

      placedParticles.push({ top: finalTop, left: finalLeft });

      return {
        ...particle,
        top: `${finalTop}%`,
        left: `${finalLeft}%`,
      };
    });
  }, []);

  const [activeParticle, setActiveParticle] = useState<ParticleInstance | null>(
    null
  );
  const [cursorPosition, setCursorPosition] = useState({ x: 0, y: 0 });
  const [cursorVisible, setCursorVisible] = useState(false);
  const [hoveredId, setHoveredId] = useState<ParticleId | null>(null);

  useEffect(() => {
    console.debug("hoveredId changed", hoveredId);
  }, [hoveredId]);

  const handleActivate = (particle: ParticleInstance) => {
    console.debug("activate", particle.id);
    setActiveParticle(particle);
    setHoveredId(particle.id);
  };

  const handlePointerLeave = (particleId?: ParticleId) => {
    const idToClear = particleId ?? hoveredId;
    console.debug("pointer leave", idToClear);
    if (idToClear) {
      setHoveredId((current) => (current === idToClear ? null : current));
    }
    setActiveParticle(null);
  };

  return (
    <Box
      component="main"
      role="main"
      sx={{
        minHeight: "100vh",
        minWidth: "100vw",
        position: "relative",
        overflow: "hidden",
        cursor: "crosshair",
      }}
      onPointerMove={(event) => {
        setCursorPosition({ x: event.clientX + 30, y: event.clientY + 40 });
        setCursorVisible(true);
      }}
      onPointerLeave={() => {
        setCursorVisible(false);
      }}
    >
      <Box
        sx={{
          position: "relative",
          zIndex: 210,
          display: "flex",
          justifyContent: "center",
        }}
      >
        <ProcessingHeader currentStep={0} prevRoute="/mist" nextRoute="/discover-summary" />
      </Box>
      <Typography
        variant="body1"
        sx={{
          textAlign: "center",
          top: 150,
          position: "absolute",
          left: 0,
          right: 0,
          fontWeight: 600,
          fontFamily: "Inter",
          fontSize: { xs: "1rem", md: "1.5rem" },
        }}
      >
        Hover over each particle to learn more.
      </Typography>
      {particleInstances.map((particle) => {
        const isActive = hoveredId === particle.id;
        return (
          <motion.img
            key={particle.id}
            src={particle.image}
            alt={`${particle.label} particle icon`}
            initial={{ opacity: 0.55, scale: 0.9 }}
            animate={{
              opacity: isActive ? 1 : 0.55,
              scale: isActive ? 1.05 : 0.9,
            }}
            transition={{ duration: 0.2, ease: "easeOut" }}
            onPointerEnter={() => handleActivate(particle)}
            onPointerDown={() => handleActivate(particle)}
            onFocus={() => handleActivate(particle)}
            onPointerLeave={() => handlePointerLeave(particle.id)}
            onBlur={() => handlePointerLeave(particle.id)}
            tabIndex={0}
            style={{
              position: "absolute",
              top: particle.top,
              left: particle.left,
              width: 96,
              height: 96,
              pointerEvents: "auto",
              filter: isActive ? "blur(0px)" : "blur(5px)",
              transition:
                "filter 220ms ease, opacity 200ms ease, transform 200ms ease",
            }}
          />
        );
      })}

      {activeParticle && (
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 8 }}
          transition={{ duration: 0.18, ease: "easeOut" }}
          style={{
            position: "fixed",
            top: 150,
            left: 40,
            pointerEvents: "none",
            zIndex: 200,
          }}
        >
          <Paper
            elevation={6}
            sx={{
              px: 2.5,
              py: 2,
              maxWidth: 320,
              borderRadius: 3,
              boxShadow: 6,
              pointerEvents: "none",
              backgroundColor: "#F5F5F5",
              opacity: 0.85,
            }}
          >
            <Chip
              label={activeParticle.label}
              sx={{
                mb: 1.5,
                fontWeight: 600,
                fontFamily: "Inter",
                backgroundColor:
                  particleColors[activeParticle.id].backgroundColor,
                color: particleColors[activeParticle.id].textColor,
              }}
              aria-hidden
            />
            <Typography
              variant="body1"
              sx={{ ml: 0.5, mb: 5, color: "#000000", fontWeight: 500, fontFamily: "Inter" }}
            >
              {activeParticle.description}
            </Typography>
            <Box sx={{ mb: 2, display: "flex", gap: 1, alignItems: "center" }}>
              <img src={health} alt="Health Impact" />
              <Typography
                variant="body2"
                color="text.secondary"
                sx={{ fontWeight: 600, fontFamily: "Inter" }}
              >
                Health Impact
              </Typography>
            </Box>
            <Typography variant="body2" color="#000000" fontFamily="Inter">
              {activeParticle.healthImpact}
            </Typography>
          </Paper>
        </motion.div>
      )}

      <motion.img
        src={magnifierSrc}
        alt="Magnifying glass cursor"
        initial={{ opacity: 0 }}
        animate={
          cursorVisible ? { opacity: 1, scale: 3 } : { opacity: 0, scale: 0.9 }
        }
        transition={{ duration: 0.2, ease: "easeOut" }}
        style={{
          position: "fixed",
          top: cursorPosition.y - 48,
          left: cursorPosition.x - 32,
          width: 96,
          height: 96,
          pointerEvents: "none",
          zIndex: 20,
        }}
      />
    </Box>
  );
};

export default ExaminePage;
